name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build environment
      run: sudo apt-get install -y build-essential

    - name: Build users code
      working-directory: users
      run: |
        make

    - name: Build kernel code
      working-directory: kernel
      run: |
        make -f Kbuild

    - name: Run user application
      working-directory: users
      run: |
        sudo ./user

    - name: Insert kernel module
      working-directory: kernel
      run: |
        sudo insmod dummy_module.ko

    - name: Remove kernel module
      run: |
        sudo rmmod dummy_module

    - name: Check kernel module
      run: |
        lsmod | grep dummy_module
