name: Docker Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
            sudo apt-get install -y build-essential
            sudo apt-get update 
            sudo apt-get install gawk wget git diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev xterm ncurses-dev lzop
            sudo apt-get install gcc-arm-linux-gnueabihf

    - name: Build users code
      run: |
        make
